name: Deploy ssg site to github pages

on:
    push:
        branches: 
            - master

jobs: 
    build:
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            pages: write
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 23.10.0

            - run: npm ci

            - name: build static site
              env: 
                NUXT_APP_BASE_URL: /${{ github.event.repository.name }}/
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: .output/public
    
    deploy: 
        needs: build

        permissions: 
            contents: read
            pages: write
            id-token: write

        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to gihub pages
              uses: actions/deploy-pages@v4
              id: deployment

